services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080,http://localhost,http://localhost:4000
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  server:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    build: './server'
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src
